services:

  db:
    container_name: postgres_db
    image: postgres:17.3
    hostname: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d booking_app"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - app.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - booking_net
    ports:
      - "5432:5432"
    restart: always

  api:
    container_name: booking_app
    build: .
    env_file:
      - app.env
    networks:
      - booking_net
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - application:/application
    depends_on:
      - db
    ports:
      - 8000:8000

networks:
  booking_net:
    driver: bridge

volumes:
  postgres-data:
  application: